### ISSUE TITLE
API请求返回错误信息时抛出的是NetworkError（而非ActionFailed）

### ISSUE THREAD

**Issue by ssttkkl** [nonebot/adapter-telegram#19]
例如如下代码，status code 400并非**unexpected**。根据定义，抛出ActionFailed是否更合适？

```python
    try:
        result = await bot.get_chat(chat_id=114514)
        print(result)
    except Exception as e:
        logger.exception(e)
```

结果：
```python
11-16 13:25:14 [ERROR] nonebot_test | <NetWorkError message=HTTP request received unexpected 400 b'{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}'>
Traceback (most recent call last):
  File "C:\Users\huang\PycharmProjects\kuraku-kook\bot.py", line 24, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\huang\PycharmProjects\kuraku-kook\venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\huang\PycharmProjects\kuraku-kook\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\huang\PycharmProjects\kuraku-kook\venv\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\huang\PycharmProjects\kuraku-kook\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\huang\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\huang\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\huang\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\huang\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\huang\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\huang\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\huang\PycharmProjects\kuraku-kook\venv\lib\site-packages\nonebot\utils.py", line 157, in run_coro_with_catch
    return await coro
  File "C:\Users\huang\PycharmProjects\kuraku-kook\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\Users\huang\PycharmProjects\kuraku-kook\src\nonebot-test\src\nonebot_test\__init__.py", line 8, in on_bot_connect
    result = await bot.get_chat(chat_id=114514)
  File "C:\Users\huang\PycharmProjects\kuraku-kook\venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 116, in call_api
    raise exception
  File "C:\Users\huang\PycharmProjects\kuraku-kook\venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\huang\PycharmProjects\kuraku-kook\venv\lib\site-packages\nonebot\adapters\telegram\adapter.py", line 215, in _call_api
    raise NetworkError(
nonebot.adapters.telegram.exception.NetworkError: <NetWorkError message=HTTP request received unexpected 400 b'{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}'>

```

**Comment by j1g5awi** [comment]
错误处理的逻辑尚未完成，所以就都抛到 `NetworkError` 了。
