### ISSUE TITLE
机器人处理涉及群组相关信息时的报错

### ISSUE THREAD

**Issue by NekoAria** [nonebot/adapter-telegram#2]
日志如下：
```Python

# 创建群组的同时邀请机器人

12-02 01:58:08 [ERROR] nonebot | Failed to handle event. Raw: {'update_id': 560925663, 'message': {'message_id': 5027, 'from': {'id': ****, 'is_bot': False, 'first_name': '****', 'last_name': '****', 'username': '****', 'language_code': 'zh-hans'}, 'chat': {'id': ****, 'title': 'test', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1638381488, 'group_chat_created': True}}
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nb_cli/commands/main.py", line 26, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 22, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 278, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 256, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/bot.py", line 100, in handle_message
    await self._handle_message(msg)
> File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/bot.py", line 105, in _handle_message
    await handle_event(self, event)
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 224, in handle_event
    _, _ = TrieRule.get_value(bot, event, state)
  File "/usr/local/lib/python3.9/site-packages/nonebot/rule.py", line 142, in get_value
    message_seg = message[0]
IndexError: list index out of range
12-02 01:58:09 [ERROR] nonebot | Failed to handle event. Raw: {'update_id': 560925664, 'my_chat_member': {'chat': {'id': ****, 'title': 'test', 'type': 'group', 'all_members_are_administrators': True}, 'from': {'id': ****, 'is_bot': False, 'first_name': '****', 'last_name': '****', 'username': '****', 'language_code': 'zh-hans'}, 'date': 1638381488, 'old_chat_member': {'user': {'id': ****, 'is_bot': True, 'first_name': '****', 'username': '****'}, 'status': 'left'}, 'new_chat_member': {'user': {'id': ****, 'is_bot': True, 'first_name': '****', 'username': '****'}, 'status': 'member'}}}
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nb_cli/commands/main.py", line 26, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 22, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 278, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 256, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/bot.py", line 100, in handle_message
    await self._handle_message(msg)
> File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/bot.py", line 104, in _handle_message
    event = Event.parse_event(message)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/event.py", line 41, in parse_event
    return cls._parse_event(obj)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/event.py", line 36, in _parse_event
    return map[post_type].parse_event(obj[post_type])
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/event.py", line 43, in parse_event
    return cls.parse_obj(obj)
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
TypeError: Can't instantiate abstract class ChatMemberUpdatedEvent with abstract methods get_event_name, get_type

# 将机器人移出群组

12-02 02:01:14 [ERROR] nonebot | Failed to handle event. Raw: {'update_id': 560925665, 'my_chat_member': {'chat': {'id': ****, 'title': 'test', 'type': 'group', 'all_members_are_administrators': True}, 'from': {'id': ****, 'is_bot': False, 'first_name': '****', 'last_name': '****', 'username': '****', 'language_code': 'zh-hans'}, 'date': 1638381674, 'old_chat_member': {'user': {'id': ****, 'is_bot': True, 'first_name': '****', 'username': '****'}, 'status': 'member'}, 'new_chat_member': {'user': {'id': ****, 'is_bot': True, 'first_name': '****', 'username': '****'}, 'status': 'left'}}}
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nb_cli/commands/main.py", line 26, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 22, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 278, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 256, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/bot.py", line 100, in handle_message
    await self._handle_message(msg)
> File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/bot.py", line 104, in _handle_message
    event = Event.parse_event(message)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/event.py", line 41, in parse_event
    return cls._parse_event(obj)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/event.py", line 36, in _parse_event
    return map[post_type].parse_event(obj[post_type])
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/event.py", line 43, in parse_event
    return cls.parse_obj(obj)
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
TypeError: Can't instantiate abstract class ChatMemberUpdatedEvent with abstract methods get_event_name, get_type
12-02 02:01:14 [ERROR] nonebot | Failed to handle event. Raw: {'update_id': 560925666, 'message': {'message_id': 5028, 'from': {'id': ****, 'is_bot': False, 'first_name': '****', 'last_name': '****', 'username': '****', 'language_code': 'zh-hans'}, 'chat': {'id': ****, 'title': 'test', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1638381674, 'left_chat_participant': {'id': ****, 'is_bot': True, 'first_name': '****', 'username': '****'}, 'left_chat_member': {'id': ****, 'is_bot': True, 'first_name': '****', 'username': '****'}}}
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nb_cli/commands/main.py", line 26, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 22, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 278, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 256, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/bot.py", line 100, in handle_message
    await self._handle_message(msg)
> File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/bot.py", line 105, in _handle_message
    await handle_event(self, event)
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 224, in handle_event
    _, _ = TrieRule.get_value(bot, event, state)
  File "/usr/local/lib/python3.9/site-packages/nonebot/rule.py", line 142, in get_value
    message_seg = message[0]
IndexError: list index out of range

# 再把机器人邀请进群组

12-02 02:04:08 [ERROR] nonebot | Failed to handle event. Raw: {'update_id': 560925671, 'my_chat_member': {'chat': {'id': ****, 'title': 'test', 'type': 'group', 'all_members_are_administrators': True}, 'from': {'id': ****, 'is_bot': False, 'first_name': '****', 'last_name': '****', 'username': '****', 'language_code': 'zh-hans'}, 'date': 1638381848, 'old_chat_member': {'user': {'id': ****, 'is_bot': True, 'first_name': '****', 'username': '****'}, 'status': 'left'}, 'new_chat_member': {'user': {'id': ****, 'is_bot': True, 'first_name': '****', 'username': '****'}, 'status': 'member'}}}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/bot.py", line 100, in handle_message
    await self._handle_message(msg)
> File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/bot.py", line 104, in _handle_message
    event = Event.parse_event(message)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/event.py", line 41, in parse_event
    return cls._parse_event(obj)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/event.py", line 36, in _parse_event
    return map[post_type].parse_event(obj[post_type])
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/event.py", line 43, in parse_event
    return cls.parse_obj(obj)
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
TypeError: Can't instantiate abstract class ChatMemberUpdatedEvent with abstract methods get_event_name, get_type
12-02 02:04:08 [ERROR] nonebot | Failed to handle event. Raw: {'update_id': 560925672, 'message': {'message_id': 5031, 'from': {'id': ****, 'is_bot': False, 'first_name': '****', 'last_name': '****', 'username': '****', 'language_code': 'zh-hans'}, 'chat': {'id': ****, 'title': 'test', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1638381848, 'new_chat_participant': {'id': ****, 'is_bot': True, 'first_name': '****', 'username': '****'}, 'new_chat_member': {'id': ****, 'is_bot': True, 'first_name': '****', 'username': '****'}, 'new_chat_members': [{'id': ****, 'is_bot': True, 'first_name': '****', 'username': '****'}]}}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/bot.py", line 100, in handle_message
    await self._handle_message(msg)
> File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/telegram/bot.py", line 105, in _handle_message
    await handle_event(self, event)
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 224, in handle_event
    _, _ = TrieRule.get_value(bot, event, state)
  File "/usr/local/lib/python3.9/site-packages/nonebot/rule.py", line 142, in get_value
    message_seg = message[0]
IndexError: list index out of range
```

**Comment by j1g5awi** [comment]
我默认把所有带`message`字段的事件解析为了`MessageEvent`，但这个事件应该解析为`NoticeEvent`。

我还没有写`NoticeEvent`的支持和分发，希望下个版本能完成。

**Comment by j1g5awi** [comment]
Fixed in 2d20524b610838d2c934594a70c127a13ec07415
