### ISSUE TITLE
关于注册的轮询间隔和异常处理

### ISSUE THREAD

**Issue by NekoAria** [nonebot/adapter-telegram#3]
我发现机器人挂着没几分钟就会报错 `Unexpected exception occurred while http polling` ，是否有什么办法进行异常处理？
相关日志如下：
```Python
12-02 02:01:24 [ERROR] nonebot | Unexpected exception occurred while http polling
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/h2/connection.py", line 224, in process_input
    func, target_state = self._transitions[(self.state, input_)]
KeyError: (<ConnectionState.CLOSED: 3>, <ConnectionInputs.RECV_WINDOW_UPDATE: 13>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nb_cli/commands/main.py", line 26, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 22, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 278, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 256, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 433, in _http_loop
    response = await session.request(request.method,
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1481, in request
    response = await self.send(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1568, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1604, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1640, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1681, in _send_single_request
    ) = await transport.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 283, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 234, in handle_async_request

HOST=127.0.0.1
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 148, in handle_async_request
    return await self.connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http2.py", line 165, in handle_async_request
    return await h2_stream.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http2.py", line 344, in handle_async_request
    status_code, headers = await self.receive_response(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http2.py", line 419, in receive_response
    event = await self.connection.wait_for_event(self.stream_id, timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http2.py", line 242, in wait_for_event
    await self.receive_events(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http2.py", line 253, in receive_events
    events = self._h2_state.receive_data(data)
  File "/usr/local/lib/python3.9/site-packages/h2/connection.py", line 1463, in receive_data
    events.extend(self._receive_frame(frame))
  File "/usr/local/lib/python3.9/site-packages/h2/connection.py", line 1486, in _receive_frame
    frames, events = self._frame_dispatch_table[frame.__class__](frame)
  File "/usr/local/lib/python3.9/site-packages/h2/connection.py", line 1731, in _receive_window_update_frame
    events = self.state_machine.process_input(
  File "/usr/local/lib/python3.9/site-packages/h2/connection.py", line 228, in process_input
    raise ProtocolError(
h2.exceptions.ProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED

12-02 02:08:24 [ERROR] nonebot | Unexpected exception occurred while http polling
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/h2/connection.py", line 224, in process_input
    func, target_state = self._transitions[(self.state, input_)]
KeyError: (<ConnectionState.CLOSED: 3>, <ConnectionInputs.RECV_WINDOW_UPDATE: 13>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 433, in _http_loop
    response = await session.request(request.method,
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1481, in request
    response = await self.send(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1568, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1604, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1640, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1681, in _send_single_request
    ) = await transport.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 283, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 234, in handle_async_request
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 148, in handle_async_request
    return await self.connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http2.py", line 165, in handle_async_request
    return await h2_stream.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http2.py", line 344, in handle_async_request
    status_code, headers = await self.receive_response(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http2.py", line 419, in receive_response
    event = await self.connection.wait_for_event(self.stream_id, timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http2.py", line 242, in wait_for_event
    await self.receive_events(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http2.py", line 253, in receive_events
    events = self._h2_state.receive_data(data)
  File "/usr/local/lib/python3.9/site-packages/h2/connection.py", line 1463, in receive_data
    events.extend(self._receive_frame(frame))
  File "/usr/local/lib/python3.9/site-packages/h2/connection.py", line 1486, in _receive_frame
    frames, events = self._frame_dispatch_table[frame.__class__](frame)
  File "/usr/local/lib/python3.9/site-packages/h2/connection.py", line 1731, in _receive_window_update_frame
    events = self.state_machine.process_input(
  File "/usr/local/lib/python3.9/site-packages/h2/connection.py", line 228, in process_input
    raise ProtocolError(
h2.exceptions.ProtocolError: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED
```

以及，是否默认的轮询间隔 0.01 太短了？
https://github.com/nonebot/adapter-telegram/blob/bcd0ec17ab7c111db276296ade9a20213f718d21/nonebot/adapters/telegram/bot.py#L70-L81

**Comment by j1g5awi** [comment]
http2 的问题，需要你手动把NoneBot2 包里的 driver 文件（`nonebot/drivers/fastapi.py`）里的

```python
async with httpx.AsyncClient(http2=True) as session:
```

改成

```python
async with httpx.AsyncClient(http2=False) as session:
```

**Comment by j1g5awi** [comment]
轮询间隔是正常的，如果你觉得太快了可以改成其他

**Comment by j1g5awi** [comment]
另外目前 long polling 会经常出现 Timeout，这个是因为 NoneBot2 并没有真正的长轮询，只是在不停地发送请求。

**Comment by NekoAria** [comment]
> http2 的问题，需要你手动把NoneBot2 包里的 driver 文件（`nonebot/drivers/fastapi.py`）里的
> 
> ```python
> async with httpx.AsyncClient(http2=True) as session:
> ```
> 
> 改成
> 
> ```python
> async with httpx.AsyncClient(http2=False) as session:
> ```

试过了，没解决，还是挂一段时间就报上面的错。

另外，我还试了把 bot.py 里的 HTTPPollingSetup 改为：

```Python
HTTPPollingSetup( 
  "telegram", 
  cls.telegram_config.token.split(":", maxsplit=1)[0], 
  f"{cls.telegram_config.api_server}bot{cls.telegram_config.token}/getUpdates", 
  "post", 
  b"", 
  {}, 
  "2.0", 
  0.3, 
) 
```
同样没解决。

**Comment by NekoAria** [comment]
话说，那个间隔我觉得也加入可配置项比较好。
我看了一些 Telegram Bot 项目，它们的轮询间隔好像都是可配置的。

**Comment by NekoAria** [comment]
似乎很多 API 的封装没实现，比如官方文档中的 sendMediaGroup 。
本来想测试一次发送多图，然后发现只有 bot.pyi 里有提到 send_media_group 。

---

我也会一点 Python ，但是 Telegram 的 API 不是很熟悉，就算想出一份力写一些，恐怕也没那么快。

---

不过比起这个问题，这个轮询的机制不改也没法用，一直发送请求只要断开连接，机器人就下线了。

**Comment by j1g5awi** [comment]
> > http2 的问题，需要你手动把NoneBot2 包里的 driver 文件（`nonebot/drivers/fastapi.py`）里的
> > ```python
> > async with httpx.AsyncClient(http2=True) as session:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 改成
> > ```python
> > async with httpx.AsyncClient(http2=False) as session:
> > ```
> 
> 试过了，没解决，还是挂一段时间就报上面的错。
> 
> 另外，我还试了把 bot.py 里的 HTTPPollingSetup 改为：
> 
> ```python
> HTTPPollingSetup( 
>   "telegram", 
>   cls.telegram_config.token.split(":", maxsplit=1)[0], 
>   f"{cls.telegram_config.api_server}bot{cls.telegram_config.token}/getUpdates", 
>   "post", 
>   b"", 
>   {}, 
>   "2.0", 
>   0.3, 
> ) 
> ```
> 
> 同样没解决。

有没有可能你改的文件不是 bot 所在环境的文件（

**Comment by j1g5awi** [comment]
> 话说，那个间隔我觉得也加入可配置项比较好。 我看了一些 Telegram Bot 项目，它们的轮询间隔好像都是可配置的。

下个版本将会加入

**Comment by j1g5awi** [comment]
> 似乎很多 API 的封装没实现，比如官方文档中的 sendMediaGroup 。 本来想测试一次发送多图，然后发现只有 bot.pyi 里有提到 send_media_group 。

`bot.pyi`和`model.py`因为是纯粹的复制粘贴所以是最先写好的。

**Comment by NekoAria** [comment]
> 有没有可能你改的文件不是 bot 所在环境的文件（

好像是这样。
为了方便测试我重新弄了个环境，结果忘了这回事。
这次挂能超过 10 分钟了，应该是好了。

不过这样也太蠢了（
还要修改 `nonebot/drivers/fastapi.py`
