### ISSUE TITLE
为bot get updates失败重试添加时间间隔？

### ISSUE THREAD

**Issue by ssttkkl** [nonebot/adapter-telegram#41]
遇到的情况是使用socks代理，但是未安装相应包时出现的报错。

按理来说是挺简单的问题，但是由于失败重试之间没有时间间隔，直接把CPU干爆了。更要命的是我在云服务器部署的，CPU爆了ssh都连不上了（）

```
06-01 10:12:51 [ERROR] nonebot | Telegram | Get updates for bot xxxxxxxx failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/nonebot/adapters/telegram/adapter.py", line 224, in _call_api
    response = await self.request(request)
  File "/usr/local/lib/python3.10/site-packages/nonebot/internal/adapter/adapter.py", line 89, in request
    return await self.driver.request(setup)
  File "/usr/local/lib/python3.10/site-packages/nonebot/drivers/httpx.py", line 50, in request
    async with httpx.AsyncClient(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1411, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[AsyncBaseTransport]] = {
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1414, in <dictcomp>
    else self._init_proxy_transport(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1467, in _init_proxy_transport
    return AsyncHTTPTransport(
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 296, in __init__
    raise ImportError(
ImportError: Using SOCKS proxy, but the 'socksio' package is not installed. Make sure to install httpx using `pip install httpx[socks]`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 98, in run
    return asyncio.run(self._serve())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.10/site-packages/nonebot/adapters/telegram/adapter.py", line 84, in poll
    updates = await bot.get_updates(offset=update_offset, timeout=30)
  File "/usr/local/lib/python3.10/site-packages/nonebot/adapters/telegram/bot.py", line 103, in call_api
    sign.return_annotation, await super().call_api(api, **kargs)
  File "/usr/local/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
  File "/usr/local/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/usr/local/lib/python3.10/site-packages/nonebot/adapters/telegram/adapter.py", line 226, in _call_api
    raise NetworkError("HTTP request failed") from e
nonebot.adapters.telegram.exception.NetworkError: <NetWorkError message=HTTP request failed>
```

**Comment by j1g5awi** [comment]
正常情况下初始化時報錯会直接退出 poll 的 task，上次合 PR 的時候把這個错误处理合没了。

fix in a5abc9a8ff070058b8260e3313f3afca82fef6ff

**Comment by j1g5awi** [comment]
Closed due to no reply for a long time
