### ISSUE TITLE
根据指南添加TG配置提示不是有效列表，如何解决呢

### ISSUE THREAD

**Issue by getSilver** [nonebot/adapter-telegram#52]
根据指南在.env.prod添加机器人配置提示不是有效列表，去掉配置能正常启动
telegram_bots = [{"token": "1234567890:ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHI", "is_webhook": True}]
报错
Traceback (most recent call last):
  File "/root/tgbot/Probot/bot.py", line 8, in <module>
    driver.register_adapter(TelegramAdapter)
  File "/root/tgbot/tgbotenv/lib/python3.10/site-packages/nonebot/internal/drive              r/driver.py", line 90, in register_adapter
    self._adapters[name] = adapter(self, **kwargs)
  File "/root/tgbot/tgbotenv/lib/python3.10/site-packages/nonebot/adapters/teleg              ram/adapter.py", line 32, in __init__
    self.adapter_config = AdapterConfig(**self.config.dict())
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AdapterConfig
telegram_bots
  value is not a valid list (type=type_error.list)

**Comment by j1g5awi** [comment]
dotenv 只识别小写的 true

**Comment by j1g5awi** [comment]
Closed due to no reply for a long time
