### ISSUE TITLE
Event 解析错误：Error when parsing event

### ISSUE THREAD

**Issue by wanakiki** [nonebot/adapter-telegram#65]
使用 nb-cli 创建项目并配置机器人 token 之后，无法根据机器人获取的消息确定当前的 event 类型。

```no
02-15 15:28:10 [ERROR] nonebot | Telegram | Error when parsing event {'update_id': 3268, 'message': {'message_id': 25, 'from': {'id': 123465, 'is_bot': False, 'first_name': 'Aradbcde', 'username': 'aradbcde_p', 'language_code': 'zh-hans'}, 'date': 1707982089, 'chat': {'id': 123465, 'type': 'private', 'username': 'aradbcde_p', 'first_name': 'Aradbcde'}}}
```

初步排查后发现消息体中并不包含 text 字段，请问这可能是什么原因导致的？

环境信息与具体的报错内容如下：

```no
apps are exposed on your $PATH
   package nb-cli 1.2.6, installed using Python 3.10.12
    - nb
```

```no
~/nonebot-workspace/my-bot$ nb run
使用 Python: /home/wk/nonebot-workspace/my-bot/.venv/bin/python
/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
02-15 15:27:28 [SUCCESS] nonebot | NoneBot is initializing...
02-15 15:27:28 [INFO] nonebot | Current Env: prod
02-15 15:27:28 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
02-15 15:27:28 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
02-15 15:27:28 [SUCCESS] nonebot | Running NoneBot...
02-15 15:27:28 [INFO] uvicorn | Started server process [14548]
02-15 15:27:28 [INFO] uvicorn | Waiting for application startup.
02-15 15:27:28 [INFO] uvicorn | Application startup complete.
02-15 15:27:28 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)
02-15 15:27:29 [INFO] nonebot | Telegram | Delete old webhook
02-15 15:27:30 [INFO] nonebot | Telegram | Start poll
02-15 15:28:10 [ERROR] nonebot | Telegram | Error when parsing event {'update_id': 3268, 'message': {'message_id': 25, 'from': {'id': 123465, 'is_bot': False, 'first_name': 'Aradbcde', 'username': 'aradbcde_p', 'language_code': 'zh-hans'}, 'date': 1707982089, 'chat': {'id': 123465, 'type': 'private', 'username': 'aradbcde_p', 'first_name': 'Aradbcde'}}}
Traceback (most recent call last):
  File "/home/wk/nonebot-workspace/my-bot/bot.py", line 14, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 185, in run
    uvicorn.run(
  File "/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/telegram/adapter.py", line 43, in __handle_update
    event = Event.parse_event(update)
  File "/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/telegram/event.py", line 80, in parse_event
    return getattr(cls, f"_{cls.__name__}__parse_event")(obj)
  File "/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/telegram/event.py", line 63, in __parse_event
    event = event_map[post_type].parse_event(obj[post_type])
  File "/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/telegram/event.py", line 80, in parse_event
    return getattr(cls, f"_{cls.__name__}__parse_event")(obj)
  File "/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/telegram/event.py", line 158, in __parse_event
    event = event_map[message_type].parse_event(obj)
  File "/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/telegram/event.py", line 82, in parse_event
    return cls._parse_event(obj)
  File "/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/telegram/event.py", line 75, in _parse_event
    return cls.parse_obj(obj)
  File "/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/pydantic/main.py", line 1072, in parse_obj
    return cls.model_validate(obj)
  File "/home/wk/nonebot-workspace/my-bot/.venv/lib/python3.10/site-packages/pydantic/main.py", line 509, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 10 validation errors for PrivateMessageEvent
forward_from
  Field required [type=missing, input_value={'message_id': 25, 'from'...'first_name': 'Aradbcde'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
forward_from_chat
  Field required [type=missing, input_value={'message_id': 25, 'from'...'first_name': 'Aradbcde'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
forward_from_message_id
  Field required [type=missing, input_value={'message_id': 25, 'from'...'first_name': 'Aradbcde'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
forward_signature
  Field required [type=missing, input_value={'message_id': 25, 'from'...'first_name': 'Aradbcde'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
forward_sender_name
  Field required [type=missing, input_value={'message_id': 25, 'from'...'first_name': 'Aradbcde'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
forward_date
  Field required [type=missing, input_value={'message_id': 25, 'from'...'first_name': 'Aradbcde'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
via_bot
  Field required [type=missing, input_value={'message_id': 25, 'from'...'first_name': 'Aradbcde'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
has_protected_content
  Field required [type=missing, input_value={'message_id': 25, 'from'...'first_name': 'Aradbcde'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
media_group_id
  Field required [type=missing, input_value={'message_id': 25, 'from'...'first_name': 'Aradbcde'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
author_signature
  Field required [type=missing, input_value={'message_id': 25, 'from'...'first_name': 'Aradbcde'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
^C02-15 15:28:15 [INFO] uvicorn | Shutting down
02-15 15:28:15 [INFO] uvicorn | Waiting for application shutdown.
02-15 15:28:15 [INFO] uvicorn | Application shutdown complete.
02-15 15:28:15 [INFO] uvicorn | Finished server process [14548]

```

**Comment by j1g5awi** [comment]
NoneBot2 新版兼容了 pydantic v2，但 telegram 适配器没有兼容。
你需要锁定 pydantic 版本在 v1 或者安装最新 commit的 telegram 适配器。

**Comment by wanakiki** [comment]
更换最新的适配器之后正常工作，感谢！
