### ISSUE TITLE
BUG: 使用 aiohttp driver 会导致发送含非英文文件名的本地文件失败

### ISSUE THREAD

**Issue by Ailitonia** [nonebot/adapter-telegram#67]
~~又一个 #43~~

## 环境

- Windows 11 23H2
- Python 3.11.8
- nonebot2==2.2.1
- nonebot-adapter-telegram==0.1.0b17

## 问题描述

使用同一本地图片重命名为不同文件名并发送:

```python3
from nonebot import on_command, logger
from nonebot.matcher import Matcher

from nonebot.adapters.telegram.message import File


@on_command('pic_test').handle()
async def _(matcher: Matcher):
    try:
        await matcher.send(File.photo(file=r'E:\cat.jpg'))
    except Exception as e:
        logger.exception(e)

    try:
        await matcher.send(File.photo(file=r'E:\猫.jpg'))
    except Exception as e:
        logger.exception(e)

    try:
        await matcher.send(File.photo(file=r'E:\ねこ.jpg'))
    except Exception as e:
        logger.exception(e)
```

使用 `httpx` 驱动器: 一切正常

```python3
03-31 20:37:25 [INFO] nonebot | Event will be handled by Matcher(type='message', module=test.v2.telegram_test, lineno=17)
03-31 20:37:25 [DEBUG] nonebot | Running Matcher(type='message', module=test.v2.telegram_test, lineno=17)
03-31 20:37:25 [DEBUG] nonebot | Running handler Dependent(call=_)
03-31 20:37:25 [DEBUG] nonebot | Telegram | Calling API sendPhoto
03-31 20:37:29 [DEBUG] nonebot | Telegram | Calling API sendPhoto
03-31 20:37:32 [DEBUG] nonebot | Telegram | Calling API sendPhoto
03-31 20:37:35 [INFO] nonebot | Matcher(type='message', module=test.v2.telegram_test, lineno=17) running complete
03-31 20:37:35 [DEBUG] nonebot | Checking for matchers completed
```

使用 `aiohttp` 驱动器: ~~后两张图寄了~~ 异常 `ValueError: Empty response`

```python3
03-31 20:38:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=test.v2.telegram_test, lineno=17)
03-31 20:38:36 [DEBUG] nonebot | Running Matcher(type='message', module=test.v2.telegram_test, lineno=17)
03-31 20:38:36 [DEBUG] nonebot | Running handler Dependent(call=_)
03-31 20:38:36 [DEBUG] nonebot | Telegram | Calling API sendPhoto
03-31 20:38:40 [DEBUG] nonebot | Telegram | Calling API sendPhoto
03-31 20:38:44 [ERROR] telegram_test | Empty response
Traceback (most recent call last):
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\bot.py", line 69, in <module>
    nonebot.run()
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\test\v2\telegram_test.py", line 25, in _
    await matcher.send(File.photo(file=r'E:\猫.jpg'))
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 558, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\adapters\telegram\bot.py", line 295, in send
    return await self.send_to(
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\adapters\telegram\bot.py", line 161, in send_to
    return await self.call_api(
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\adapters\telegram\bot.py", line 103, in call_api
    await super().call_api(api, **kargs)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\adapters\telegram\adapter.py", line 241, in _call_api
    raise ValueError("Empty response")
ValueError: Empty response
03-31 20:38:44 [DEBUG] nonebot | Telegram | Calling API sendPhoto
03-31 20:38:49 [ERROR] telegram_test | Empty response
Traceback (most recent call last):
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\bot.py", line 69, in <module>
    nonebot.run()
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Users\Ailit\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\test\v2\telegram_test.py", line 30, in _
    await matcher.send(File.photo(file=r'E:\ねこ.jpg'))
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 558, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\adapters\telegram\bot.py", line 295, in send
    return await self.send_to(
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\adapters\telegram\bot.py", line 161, in send_to
    return await self.call_api(
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\adapters\telegram\bot.py", line 103, in call_api
    await super().call_api(api, **kargs)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Ailit\PycharmProjects\nonebot2_miya\venv\Lib\site-packages\nonebot\adapters\telegram\adapter.py", line 241, in _call_api
    raise ValueError("Empty response")
ValueError: Empty response
03-31 20:38:49 [INFO] nonebot | Matcher(type='message', module=test.v2.telegram_test, lineno=17) running complete
```

**Comment by j1g5awi** [comment]
此問題為 AIOHTTP 默认对 MIME headers 包裹引号所致，https://github.com/nonebot/nonebot2/pull/2619 已改寫此默认行为。
