### ISSUE TITLE
getUpdates 返回类型校验 出错

### ISSUE THREAD

**Issue by SleepyAsh0191** [nonebot/adapter-telegram#73]
```
09-22 23:50:05 [DEBUG] nonebot | Telegram | Calling API getUpdates
09-22 23:50:08 [ERROR] nonebot | Telegram | Get updates for bot XXXXXXXXX failed
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\Administrator\Desktop\nonebot\madcroix-bot\.venv\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\madcroix-bot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\nonebot\madcroix-bot\.venv\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Administrator\Desktop\nonebot\madcroix-bot\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Program Files\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python312\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Program Files\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\Desktop\nonebot\madcroix-bot\.venv\Lib\site-packages\nonebot\adapters\telegram\adapter.py", line 88, in poll
    updates = await bot.get_updates(offset=update_offset, timeout=30)
  File "C:\Users\Administrator\Desktop\nonebot\madcroix-bot\.venv\Lib\site-packages\nonebot\adapters\telegram\bot.py", line 102, in call_api
    return TypeAdapter(sign.return_annotation).validate_python(
  File "C:\Users\Administrator\Desktop\nonebot\madcroix-bot\.venv\Lib\site-packages\pydantic\type_adapter.py", line 260, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for list[Update]
0.message.reply_to_message.entities.0.type
  Input should be 'mention', 'hashtag', 'cashtag', 'bot_command', 'url', 'email', 'phone_number', 'bold', 'italic', 'underline', 'strikethrough', 'spoiler', 'blockquote', 'code', 'pre', 'text_link', 'text_mention' or 'custom_emoji' [type=literal_error, input_value='expandable_blockquote', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/literal_error
```

**Comment by SleepyAsh0191** [comment]
解决方法：
model.py
```
class MessageEntity(BaseModel):
    type: Literal[
        "mention",
        "hashtag",
        "cashtag",
        "bot_command",
        "url",
        "email",
        "phone_number",
        "bold",
        "italic",
        "underline",
        "strikethrough",
        "spoiler",
        "blockquote",
        "code",
        "pre",
        "text_link",
        "text_mention",
        "custom_emoji",
        "expandable_blockquote"
    ]
    offset: int
    length: int
    url: Optional[str] = None
    user: Optional[User] = None
    language: Optional[str] = None
    custom_emoji_id: Optional[str] = None
```

**Comment by j1g5awi** [comment]
~~之前 commit 后忘记发版了……~~ **已发版**。
